[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0", default-features = false }
log = "0"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "z"

[patch.crates-io]
log = { path = "../opt/log" }